# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Deploy to Google App Engine
      uses: etereo-io/deploy-gae-action@v2.0.4
      with:
        # Service account file
        service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        # Project id
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        # Debug action
        debug: false # optional, default is 
        # Path to the yaml file
        # gae_config_path: # default is ./app.yaml
        # Disable cache
        # no_cache: # optional
